fims.settings:
  type: config_object
  label: 'Custom FIMS Settings'
  mapping:
    oauth2_client_id:
      type: string
      label: 'FIMS Instance client id'
    oauth2_client_secret:
      type: string
      label: 'Test 1'
    fims_rest_uri:
      type: string
      label: 'Test 2'
    fims_resolver_rest_uri:
      type: string
      label: 'Test 3'
